name: Sync Upstream ZFS

on:
  schedule:
    - cron: '0 16 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the 'master' branch
        uses: actions/checkout@v4
        with:
          ref: master
          token: ${{ secrets.SYNC_TOKEN }}
          fetch-depth: 0

      - name: Sync with upstream (master and tags)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # 这部分逻辑不变，因为它已经明确操作 master
          git remote add upstream https://github.com/openzfs/zfs.git
          git fetch upstream master
          git checkout master
          git reset --hard upstream/master
          git push origin master --force

          git fetch upstream --tags
          git push origin --tags
